config/routes.rb
Rails.application.routes.draw do

 get 'newcomments' => 'comments#index'

  get 'home/index'

  get 'home' => 'home#index' , path: "" 
  resources :submits, except: [:new, :index], path: '/submit' do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  get 'submit' => 'submits#new'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :submit
  validates :body, presence: true
end

app/models/submit.rb
class Submit < ApplicationRecord
    has_many :comments
    
def comment_count
  comments.length
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
def index
  @comments = Comment.all
end 

def show
end

  def create
    @submit = Submit.find(params[:submit_id])
    @comment = @submit.comments.new(body: comment_params[:body])
  
    if @comment.save
      redirect_to @submit, notice: 'Comment added'
    else
      redirect_to @submit, notice: 'Comment was not saved. Ensure you have entered a comment'
    end
  end

private

def comment_params
  params.require(:comment).permit(:body)
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = "RMIT News"     
  end
  
    before_action :set_submit, only: [:show, :edit, :update, :destroy]

  # GET /submits
  # GET /submits.json
  def index
    @submits = Submit.all
  end

  # GET /submits/1
  # GET /submits/1.json
  def show
  end

  # GET /submits/new
  def new
    @submit = Submit.new
  end

  # GET /submits/1/edit
  def edit
  end

  # POST /submits
  # POST /submits.json
  def create
    @submit = Submit.new(submit_params)

    respond_to do |format|
      if @submit.save
        format.html { redirect_to @submit, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @submit }
      else
        format.html { render :new }
        format.json { render json: @submit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submits/1
  # PATCH/PUT /submits/1.json
  def update
    respond_to do |format|
      if @submit.update(submit_params)
        format.html { redirect_to @submit, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @submit }
      else
        format.html { render :edit }
        format.json { render json: @submit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submits/1
  # DELETE /submits/1.json
  def destroy
    @submit.destroy
    respond_to do |format|
      format.html { redirect_to submits_url, notice: 'News was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submit
      @submit = Submit.find(params[:id])
    end
    
    def time
      @submit.time = Submit.find(params[:id]).updated_at
    end
      

    # Never trust parameters from the scary internet, only allow the white list through.
    def submit_params
      params.require(:submit).permit(:title, :source, :time)
    end
    
  
    
     

  
    
end

app/controllers/submits_controller.rb
class SubmitsController < ApplicationController
  before_action :set_submit, only: [:show, :edit, :update, :destroy]
  
  
  # GET /submits
  # GET /submits.json
  def index
    @submits = Submit.all
  end

  # GET /submits/1
  # GET /submits/1.json
  def show
     @comments = @submit.comments
  end

  # GET /submits/new
  def new
    @submit = Submit.new
  end

  # GET /submits/1/edit
  def edit
  end

  # POST /submits
  # POST /submits.json
  def create
    @submit = Submit.new(submit_params)

    respond_to do |format|
      if @submit.save
        format.html { redirect_to @submit, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @submit }
      else
        format.html { render :new }
        format.json { render json: @submit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submits/1
  # PATCH/PUT /submits/1.json
  def update
    respond_to do |format|
      if @submit.update(submit_params)
        format.html { redirect_to @submit, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @submit }
      else
        format.html { render :edit }
        format.json { render json: @submit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submits/1
  # DELETE /submits/1.json
  def destroy
    @submit.destroy
    respond_to do |format|
      format.html { redirect_to submits_url, notice: 'News was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submit
      @submit = Submit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submit_params
      params.require(:submit).permit(:title, :source)
    end
    
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
    

def someMethod(newID)
    
    news = Submit.find(newID)
    title = news.title
end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/submits_helper.rb
module SubmitsHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<section>
  <% @comments.each do |comment| %>
  <div>
    <p>
      <strong>
        <%= "User: ABC" %>
      </strong>

      <span>
        <%= time_ago_in_words(comment.created_at) %> ago | on:
        <%= someMethod(comment.submit_id) %>
      </span><br>
      <%= comment.body %>
    </p>
  </div>
  <% end %>
</section>

app/views/home/index.html.erb
<h1><%= @message %></h1>  
<p>From app/views/hello/index.html.erb</p>  



<table>

  <tbody>
    <% @submits.each do |submit| %>
      <tr>
        <td><%= submit.title %>  
        
        <% if submit.source? %>
            (<%= submit.source %>)
          <% end %> <br> 
        Submited by: User | <%= time_ago_in_words(submit.created_at) %> ago | 
         <%= link_to pluralize(submit.comment_count, 'comment'), submit %> </td>
        
        <td><%= link_to 'Show', submit %></td>
        <td><%= link_to 'Edit', edit_submit_path(submit) %></td>
        <td><%= link_to 'Delete', submit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td></td>
      </tr>
    <% end %>
    
   
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RMIT News</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav class="one">
     <ul>
       <%= image_tag("rmit.jpg", :alt => "RMIT icon", :size => "18x18") %> RMIT News
       <li><%= link_to "Home", home_path, :class => "one" %></li>
       <li><%= link_to "Comments", newcomments_path, :class => "one" %></li>
       <li><%= link_to "Submit", submits_path, :class => "one" %></li>
       <li><a class="one" href>Login </a></li>
     </ul>
    </nav>
  </head>

  <body>
    <%= yield %>
  </body>
  
  <div class="footer">
   <ul>
       <li><a class="one" href="https://github.com/pigfly/RMIT-CSIT-RAD/tree/master/2018_S1/assignment2">API</a></li>
       <li><a class="one" href>About</a></li>
     </ul>
</div>
</html>

app/views/submits/_form.html.erb
<%= form_for(submit) do |f| %>
  <% if submit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submit.errors.count, "error") %> prohibited this submit from being saved:</h2>

      <ul>
      <% submit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Title %>
    <%= f.text_area :title, required: true %>
  </div>

  <div class="field">
    News source (optional) :
    <%= f.text_field :source %>
  </div>

  <div class="actions">
    <%= f.submit "Submit News" %>
  </div>
<% end %>

app/views/submits/edit.html.erb
<h1>Editing Submit</h1>

<%= render 'form', submit: @submit %>

<%= link_to 'Show', @submit %> |
<%= link_to 'Back', home_path %>

app/views/submits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Submits</h1>

<table>

  <tbody>
    <% @submits.each do |submit| %>
      <tr>
        <td><%= submit.title %> (<%= submit.source %>)</td>

        <td><%= link_to 'Show', submit %></td>
        <td><%= link_to 'Edit', edit_submit_path(submit) %></td>
        <td><%= link_to 'Delete', submit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submit', new_submit_path %>

app/views/submits/new.html.erb
<h1>Submit News</h1>

<%= render 'form', submit: @submit %>

app/views/submits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @submit.title %>
</p>
<% if @submit.source? %>
<p>
  <strong>Source:</strong>
  <%= @submit.source %>
</p>
<% end %>

<div>
        <%= form_for :comment, url: submit_comments_path(@submit) do |f| %>
         
            <%= f.text_area :body, class: "form-control", placeholder: "Enter your comment here", rows: 10, required: true %>
        <br><br><div>
            <%= f.button "Add Comment" %>
        </div>
        <% end %>
</div>

<div>
      <% if @comments.present? %>
        <h3>
            Comments
        </h3>
      <% end %>
      
      <% @comments.each do |comment| %>
      <p>
        <div>
              <%= time_ago_in_words(comment.created_at) %> ago |
            <%= comment.body %>
        </div>
      </p>
      <% end %>
  </div>



<%= link_to 'Edit', edit_submit_path(@submit) %> |
<%= link_to 'Back', home_path %>